import Head from 'next/head';
import SignIn from '../components/signInLayout/signInLayout';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Hitchdoc | SignIn</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SignIn></SignIn>
        </div>
    );
}


