import Head from 'next/head';
import SignIn from '../components/signInLayout/signInLayout';

export default function Home() {
    return (
        <div>
            <Head>
                <title>Hitchdoc | SignIn</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <SignIn></SignIn>
        </div>
    );
}

// import { useSession, signIn, signOut } from "next-auth/react";

// export default function Component() {
//   const { data: session } = useSession();
//   console.log(session)
//   if (session) {
//       return (
//           <>
//         Signed in as {session.user.email} <br />
//         <button onClick={() => signOut()}>Sign out</button>
//       </>
//     )
// }
// return (
//     <>
//       Not signed in <br />
//       <button onClick={() => signIn()}>Sign in</button>
//     </>
//   )
// }


